# Generated by Django 5.2.4 on 2025-07-31 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('mot_pass', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cin', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('mot_pass', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cin', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodePostale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reclamation', models.CharField(choices=[('pollution', 'Pollution'), ('dechet', 'Déchets'), ('autre', 'Autre')], max_length=50)),
                ('date_re', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reclamations/')),
                ('localisation', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=20)),
                ('description', models.TextField()),
                ('priorite', models.IntegerField(default=1)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.citoyen')),
                ('code_postale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.codepostale')),
            ],
        ),
    ]
