# Generated by Django 5.2.4 on 2025-08-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.citoyen'),
        ),
    ]
