# Generated by Django 5.2.4 on 2025-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reclamation_citoyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='type_reclamation',
            field=models.CharField(choices=[('Trottoir dégradé ou impraticable', 'Trottoir dégradé ou impraticable'), ('Espaces verts non entretenus', 'Espaces verts non entretenus'), ('Éclairage insuffisant dans une zone', 'Éclairage insuffisant dans une zone'), ('Dégradation d’un bâtiment public', 'Dégradation d’un bâtiment public'), ('Clôture ou mur endommagé', 'Clôture ou mur endommagé'), ('autre', 'Autre')], max_length=50),
        ),
    ]
