# Generated by Django 5.2.4 on 2025-08-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reclamation_type_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='prenom',
            field=models.CharField(default=0, max_length=110),
            preserve_default=False,
        ),
    ]
