# Generated by Django 5.2.4 on 2025-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agent_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codepostale',
            old_name='num',
            new_name='zip',
        ),
        migrations.AddField(
            model_name='codepostale',
            name='cite',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codepostale',
            name='deleg',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codepostale',
            name='gov',
            field=models.CharField(default='Ariana', max_length=100),
            preserve_default=False,
        ),
    ]
